// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messaging.proto

package com.example.grpcdemo;

public final class GrpcdemoProto {
  private GrpcdemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcdemo_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcdemo_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcdemo_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcdemo_MessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcdemo_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcdemo_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpcdemo_MessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpcdemo_MessagesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Messaging.proto\022\010grpcdemo\"G\n\016MessageRe" +
      "quest\022\021\n\tsender_id\030\001 \001(\t\022\024\n\014recipient_id" +
      "\030\002 \001(\t\022\014\n\004text\030\003 \001(\t\"5\n\017MessageResponse\022" +
      "\022\n\nmessage_id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\"\036\n\013U" +
      "serRequest\022\017\n\007user_id\030\001 \001(\t\"?\n\020MessagesR" +
      "esponse\022+\n\010messages\030\001 \003(\0132\031.grpcdemo.Mes" +
      "sageResponse2\240\001\n\020MessagingService\022B\n\013Sen" +
      "dMessage\022\030.grpcdemo.MessageRequest\032\031.grp" +
      "cdemo.MessageResponse\022H\n\023GetReceivedMess" +
      "ages\022\025.grpcdemo.UserRequest\032\032.grpcdemo.M" +
      "essagesResponseB\'\n\024com.example.grpcdemoB" +
      "\rGrpcdemoProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpcdemo_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpcdemo_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcdemo_MessageRequest_descriptor,
        new java.lang.String[] { "SenderId", "RecipientId", "Text", });
    internal_static_grpcdemo_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpcdemo_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcdemo_MessageResponse_descriptor,
        new java.lang.String[] { "MessageId", "Status", });
    internal_static_grpcdemo_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpcdemo_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcdemo_UserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_grpcdemo_MessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpcdemo_MessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpcdemo_MessagesResponse_descriptor,
        new java.lang.String[] { "Messages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
