// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messaging.proto

package com.example.grpcdemo;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcdemo.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
