// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messaging.proto

package com.example.grpcdemo;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcdemo.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender_id = 1;</code>
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string recipient_id = 2;</code>
   */
  java.lang.String getRecipientId();
  /**
   * <code>string recipient_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getRecipientIdBytes();

  /**
   * <code>string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
