// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messaging.proto

package com.example.grpcdemo;

public interface MessagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcdemo.MessagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .grpcdemo.MessageResponse messages = 1;</code>
   */
  java.util.List<com.example.grpcdemo.MessageResponse> 
      getMessagesList();
  /**
   * <code>repeated .grpcdemo.MessageResponse messages = 1;</code>
   */
  com.example.grpcdemo.MessageResponse getMessages(int index);
  /**
   * <code>repeated .grpcdemo.MessageResponse messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .grpcdemo.MessageResponse messages = 1;</code>
   */
  java.util.List<? extends com.example.grpcdemo.MessageResponseOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .grpcdemo.MessageResponse messages = 1;</code>
   */
  com.example.grpcdemo.MessageResponseOrBuilder getMessagesOrBuilder(
      int index);
}
