// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messaging.proto

package com.example.grpcdemo;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcdemo.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
